// 用户管理
const dictDetail = {
  content: [
    {
      createTime: "2019-10-27 20:31:36",
      dict: { id: 1 },
      dictSort: 1,
      id: 1,
      label: "激活",
      value: "true"
    },
    { dict: { id: 1 }, dictSort: 2, id: 2, label: "禁用", value: "false" }
  ],
  totalCount: 2
};
const users = {
  content: [
    {
      avatarPath: "/home/eladmin/avatar/avatar.jpeg",
      createBy: "admin",
      createTime: "2020-05-05 11:15:49",
      dept: { id: 2, name: "研发部" },
      email: "test@el-admin.vip",
      enabled: true,
      gender: "男",
      id: 2,
      jobs: [{ id: 12, name: "软件测试" }],
      nickName: "测试",
      phone: "18888888889",
      roles: [{ dataScope: "自定义", id: 2, level: 2, name: "普通用户" }],
      updateTime: "2020-09-05 10:43:38",
      username: "test"
    },
    {
      avatarName: "avatar.jpeg",
      avatarPath: "/home/eladmin/avatar/avatar.jpeg",
      createTime: "2018-08-23 09:11:56",
      dept: { id: 2, name: "研发部" },
      email: "admin@el-admin.vip",
      enabled: true,
      gender: "男",
      id: 1,
      jobs: [{ id: 11, name: "全栈开发" }],
      nickName: "管理员",
      phone: "18888888888",
      pwdResetTime: "2020-05-03 16:38:31",
      roles: [{ dataScope: "全部", id: 1, level: 1, name: "超级管理员" }],
      updateTime: "2020-09-05 10:43:31",
      username: "admin"
    }
  ],
  totalCount: 2
};
const dept = {
  content: [
    {
      createBy: "admin",
      createTime: "2019-03-25 11:04:50",
      deptSort: 0,
      enabled: true,
      hasChildren: true,
      id: 7,
      label: "华南分部",
      leaf: false,
      name: "华南分部",
      subCount: 2,
      updateTime: "2020-06-08 12:08:56"
    },
    {
      createBy: "admin",
      createTime: "2019-03-25 11:04:53",
      deptSort: 1,
      enabled: true,
      hasChildren: true,
      id: 8,
      label: "华北分部",
      leaf: false,
      name: "华北分部",
      subCount: 2,
      updateTime: "2020-05-14 12:54:00"
    }
  ],
  totalCount: 2
};
// 角色管理
const apiRoles = {
  content: [
    {
      createTime: "2018-11-23 11:04:37",
      dataScope: "全部",
      depts: [],
      description: "-",
      id: 1,
      level: 1,
      menus: [
        {
          cache: false,
          component: "mnt/deployHistory/index",
          componentName: "DeployHistory",
          createTime: "2019-11-10 16:49:44",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "backup",
          id: 97,
          label: "部署备份",
          leaf: false,
          menuSort: 25,
          path: "mnt/deployHistory",
          permission: "deployHistory:list",
          pid: 90,
          subCount: 1,
          title: "部署备份",
          type: 1
        },
        {
          cache: false,
          component: "mnt/database/index",
          componentName: "Database",
          createTime: "2019-11-10 20:40:04",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "database",
          id: 98,
          label: "数据库管理",
          leaf: false,
          menuSort: 26,
          path: "mnt/database",
          permission: "database:list",
          pid: 90,
          subCount: 3,
          title: "数据库管理",
          type: 1
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 09:32:48",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 102,
          label: "删除",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "deployHistory:del",
          pid: 97,
          subCount: 0,
          title: "删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:08:33",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 103,
          label: "服务器新增",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "serverDeploy:add",
          pid: 92,
          subCount: 0,
          title: "服务器新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:08:57",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 104,
          label: "服务器编辑",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "serverDeploy:edit",
          pid: 92,
          subCount: 0,
          title: "服务器编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:09:15",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 105,
          label: "服务器删除",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "serverDeploy:del",
          pid: 92,
          subCount: 0,
          title: "服务器删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:10:03",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 106,
          label: "应用新增",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "app:add",
          pid: 93,
          subCount: 0,
          title: "应用新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:10:28",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 107,
          label: "应用编辑",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "app:edit",
          pid: 93,
          subCount: 0,
          title: "应用编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:10:55",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 108,
          label: "应用删除",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "app:del",
          pid: 93,
          subCount: 0,
          title: "应用删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:11:22",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 109,
          label: "部署新增",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "deploy:add",
          pid: 94,
          subCount: 0,
          title: "部署新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:11:41",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 110,
          label: "部署编辑",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "deploy:edit",
          pid: 94,
          subCount: 0,
          title: "部署编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:12:01",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 111,
          label: "部署删除",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "deploy:del",
          pid: 94,
          subCount: 0,
          title: "部署删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:12:43",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 112,
          label: "数据库新增",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "database:add",
          pid: 98,
          subCount: 0,
          title: "数据库新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:12:58",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 113,
          label: "数据库编辑",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "database:edit",
          pid: 98,
          subCount: 0,
          title: "数据库编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-11-17 11:13:14",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 114,
          label: "数据库删除",
          leaf: true,
          menuSort: 999,
          path: "",
          permission: "database:del",
          pid: 98,
          subCount: 0,
          title: "数据库删除",
          type: 2
        },
        {
          cache: true,
          component: "generator/preview",
          componentName: "Preview",
          createTime: "2019-11-26 14:54:36",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "java",
          id: 116,
          label: "生成预览",
          leaf: true,
          menuSort: 999,
          path: "generator/preview/:tableName",
          pid: 36,
          subCount: 0,
          title: "生成预览",
          type: 1
        },
        {
          cache: false,
          createBy: "admin",
          createTime: "2020-09-06 17:12:43",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          id: 120,
          label: "1",
          leaf: true,
          menuSort: 999,
          permission: "1",
          pid: 41,
          subCount: 0,
          title: "1",
          type: 2,
          updateTime: "2020-09-06 17:12:43"
        },
        {
          cache: false,
          createTime: "2018-12-18 15:11:29",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "system",
          id: 1,
          label: "系统管理",
          leaf: false,
          menuSort: 1,
          path: "system",
          subCount: 8,
          title: "系统管理",
          type: 0
        },
        {
          cache: false,
          component: "system/user/index",
          componentName: "User",
          createTime: "2018-12-18 15:14:44",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "peoples",
          id: 2,
          label: "用户管理",
          leaf: false,
          menuSort: 2,
          path: "user",
          permission: "user:list",
          pid: 1,
          subCount: 3,
          title: "用户管理",
          type: 1,
          updateTime: "2020-09-06 17:29:33"
        },
        {
          cache: false,
          component: "system/role/index",
          componentName: "Role",
          createTime: "2018-12-18 15:16:07",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "role",
          id: 3,
          label: "角色管理",
          leaf: false,
          menuSort: 3,
          path: "role",
          permission: "roles:list",
          pid: 1,
          subCount: 3,
          title: "角色管理",
          type: 1
        },
        {
          cache: false,
          component: "system/menu/index",
          componentName: "Menu",
          createTime: "2018-12-18 15:17:28",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 5,
          label: "菜单管理",
          leaf: false,
          menuSort: 5,
          path: "menu",
          permission: "menu:list",
          pid: 1,
          subCount: 3,
          title: "菜单管理",
          type: 1
        },
        {
          cache: false,
          createTime: "2018-12-18 15:17:48",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "monitor",
          id: 6,
          label: "系统监控",
          leaf: false,
          menuSort: 10,
          path: "monitor",
          subCount: 5,
          title: "系统监控",
          type: 0
        },
        {
          cache: true,
          component: "monitor/log/index",
          componentName: "Log",
          createTime: "2018-12-18 15:18:26",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "log",
          id: 7,
          label: "操作日志",
          leaf: true,
          menuSort: 11,
          path: "logs",
          pid: 6,
          subCount: 0,
          title: "操作日志",
          type: 1,
          updateTime: "2020-06-06 13:11:57"
        },
        {
          cache: false,
          component: "monitor/sql/index",
          componentName: "Sql",
          createTime: "2018-12-18 15:19:34",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "sqlMonitor",
          id: 9,
          label: "SQL监控",
          leaf: true,
          menuSort: 18,
          path: "druid",
          pid: 6,
          subCount: 0,
          title: "SQL监控",
          type: 1
        },
        {
          cache: false,
          createTime: "2018-12-19 13:38:16",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "zujian",
          id: 10,
          label: "组件管理",
          leaf: false,
          menuSort: 50,
          path: "components",
          subCount: 5,
          title: "组件管理",
          type: 0
        },
        {
          cache: false,
          component: "components/icons/index",
          componentName: "Icons",
          createTime: "2018-12-19 13:38:49",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "icon",
          id: 11,
          label: "图标库",
          leaf: true,
          menuSort: 51,
          path: "icon",
          pid: 10,
          subCount: 0,
          title: "图标库",
          type: 1
        },
        {
          cache: false,
          component: "tools/email/index",
          componentName: "Email",
          createTime: "2018-12-27 10:13:09",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "email",
          id: 14,
          label: "邮件工具",
          leaf: true,
          menuSort: 35,
          path: "email",
          pid: 36,
          subCount: 0,
          title: "邮件工具",
          type: 1
        },
        {
          cache: false,
          component: "components/Editor",
          componentName: "Editor",
          createTime: "2018-12-27 11:58:25",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "fwb",
          id: 15,
          label: "富文本",
          leaf: true,
          menuSort: 52,
          path: "tinymce",
          pid: 10,
          subCount: 0,
          title: "富文本",
          type: 1
        },
        {
          cache: false,
          component: "tools/storage/index",
          componentName: "Storage",
          createTime: "2018-12-31 11:12:15",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "qiniu",
          id: 18,
          label: "存储管理",
          leaf: false,
          menuSort: 34,
          path: "storage",
          permission: "storage:list",
          pid: 36,
          subCount: 3,
          title: "存储管理",
          type: 1
        },
        {
          cache: false,
          component: "tools/aliPay/index",
          componentName: "AliPay",
          createTime: "2018-12-31 14:52:38",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "alipay",
          id: 19,
          label: "支付宝工具",
          leaf: true,
          menuSort: 37,
          path: "aliPay",
          pid: 36,
          subCount: 0,
          title: "支付宝工具",
          type: 1
        },
        {
          cache: false,
          component: "",
          createTime: "2019-01-04 16:22:03",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 21,
          label: "多级菜单",
          leaf: false,
          menuSort: 900,
          path: "nested",
          subCount: 2,
          title: "多级菜单",
          type: 0,
          updateTime: "2020-06-21 17:27:35"
        },
        {
          cache: false,
          component: "",
          createTime: "2019-01-04 16:23:29",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 22,
          label: "二级菜单1",
          leaf: false,
          menuSort: 900,
          path: "menu1",
          pid: 21,
          subCount: 2,
          title: "二级菜单1",
          type: 0,
          updateTime: "2020-12-19 17:28:06"
        },
        {
          cache: false,
          component: "nested/menu2/index",
          createTime: "2019-01-04 16:23:57",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 23,
          label: "二级菜单2",
          leaf: true,
          menuSort: 999,
          path: "menu2",
          pid: 21,
          subCount: 0,
          title: "二级菜单2",
          type: 1
        },
        {
          cache: true,
          component: "nested/menu1/menu1-1",
          componentName: "Test",
          createTime: "2019-01-04 16:24:48",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 24,
          label: "三级菜单1",
          leaf: true,
          menuSort: 998,
          path: "menu1-1",
          pid: 22,
          subCount: 0,
          title: "三级菜单1",
          type: 1,
          updateTime: "2020-12-19 17:37:23"
        },
        {
          cache: false,
          component: "nested/menu1/menu1-2",
          createTime: "2019-01-07 17:27:32",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 27,
          label: "三级菜单2",
          leaf: true,
          menuSort: 999,
          path: "menu1-2",
          pid: 22,
          subCount: 0,
          title: "三级菜单2",
          type: 1
        },
        {
          cache: false,
          component: "system/timing/index",
          componentName: "Timing",
          createTime: "2019-01-07 20:34:40",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "timing",
          id: 28,
          label: "任务调度",
          leaf: false,
          menuSort: 999,
          path: "timing",
          permission: "timing:list",
          pid: 1,
          subCount: 3,
          title: "任务调度",
          type: 1
        },
        {
          cache: true,
          component: "generator/index",
          componentName: "GeneratorIndex",
          createTime: "2019-01-11 15:45:55",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "dev",
          id: 30,
          label: "代码生成",
          leaf: true,
          menuSort: 32,
          path: "generator",
          pid: 36,
          subCount: 0,
          title: "代码生成",
          type: 1
        },
        {
          cache: false,
          component: "monitor/log/errorLog",
          componentName: "ErrorLog",
          createTime: "2019-01-13 13:49:03",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "error",
          id: 32,
          label: "异常日志",
          leaf: true,
          menuSort: 12,
          path: "errorLog",
          pid: 6,
          subCount: 0,
          title: "异常日志",
          type: 1
        },
        {
          cache: false,
          component: "components/MarkDown",
          componentName: "Markdown",
          createTime: "2019-03-08 13:46:44",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "markdown",
          id: 33,
          label: "Markdown",
          leaf: true,
          menuSort: 53,
          path: "markdown",
          pid: 10,
          subCount: 0,
          title: "Markdown",
          type: 1
        },
        {
          cache: false,
          component: "components/YamlEdit",
          componentName: "YamlEdit",
          createTime: "2019-03-08 15:49:40",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "dev",
          id: 34,
          label: "Yaml编辑器",
          leaf: true,
          menuSort: 54,
          path: "yaml",
          pid: 10,
          subCount: 0,
          title: "Yaml编辑器",
          type: 1
        },
        {
          cache: false,
          component: "system/dept/index",
          componentName: "Dept",
          createTime: "2019-03-25 09:46:00",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "dept",
          id: 35,
          label: "部门管理",
          leaf: false,
          menuSort: 6,
          path: "dept",
          permission: "dept:list",
          pid: 1,
          subCount: 3,
          title: "部门管理",
          type: 1
        },
        {
          cache: false,
          component: "",
          createTime: "2019-03-29 10:57:35",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "sys-tools",
          id: 36,
          label: "系统工具",
          leaf: false,
          menuSort: 30,
          path: "sys-tools",
          subCount: 7,
          title: "系统工具",
          type: 0
        },
        {
          cache: false,
          component: "system/job/index",
          componentName: "Job",
          createTime: "2019-03-29 13:51:18",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "Steve-Jobs",
          id: 37,
          label: "岗位管理",
          leaf: false,
          menuSort: 7,
          path: "job",
          permission: "job:list",
          pid: 1,
          subCount: 3,
          title: "岗位管理",
          type: 1
        },
        {
          cache: false,
          component: "tools/swagger/index",
          componentName: "Swagger",
          createTime: "2019-03-29 19:57:53",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "swagger",
          id: 38,
          label: "接口文档",
          leaf: true,
          menuSort: 36,
          path: "swagger2",
          pid: 36,
          subCount: 0,
          title: "接口文档",
          type: 1
        },
        {
          cache: false,
          component: "system/dict/index",
          componentName: "Dict",
          createTime: "2019-04-10 11:49:04",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "dictionary",
          id: 39,
          label: "字典管理",
          leaf: false,
          menuSort: 8,
          path: "dict",
          permission: "dict:list",
          pid: 1,
          subCount: 3,
          title: "字典管理",
          type: 1
        },
        {
          cache: false,
          component: "monitor/online/index",
          componentName: "OnlineUser",
          createTime: "2019-10-26 22:08:43",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "Steve-Jobs",
          id: 41,
          label: "在线用户",
          leaf: false,
          menuSort: 10,
          path: "online",
          pid: 6,
          subCount: 1,
          title: "在线用户",
          type: 1
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 10:59:46",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 44,
          label: "用户新增",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "user:add",
          pid: 2,
          subCount: 0,
          title: "用户新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 11:00:08",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 45,
          label: "用户编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "user:edit",
          pid: 2,
          subCount: 0,
          title: "用户编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 11:00:23",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 46,
          label: "用户删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "user:del",
          pid: 2,
          subCount: 0,
          title: "用户删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:45:34",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 48,
          label: "角色创建",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "roles:add",
          pid: 3,
          subCount: 0,
          title: "角色创建",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:46:16",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 49,
          label: "角色修改",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "roles:edit",
          pid: 3,
          subCount: 0,
          title: "角色修改",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:46:51",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 50,
          label: "角色删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "roles:del",
          pid: 3,
          subCount: 0,
          title: "角色删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:55:07",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 52,
          label: "菜单新增",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "menu:add",
          pid: 5,
          subCount: 0,
          title: "菜单新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:55:40",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 53,
          label: "菜单编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "menu:edit",
          pid: 5,
          subCount: 0,
          title: "菜单编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:56:00",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 54,
          label: "菜单删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "menu:del",
          pid: 5,
          subCount: 0,
          title: "菜单删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:57:09",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 56,
          label: "部门新增",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "dept:add",
          pid: 35,
          subCount: 0,
          title: "部门新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:57:27",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 57,
          label: "部门编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "dept:edit",
          pid: 35,
          subCount: 0,
          title: "部门编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:57:41",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 58,
          label: "部门删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "dept:del",
          pid: 35,
          subCount: 0,
          title: "部门删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:58:27",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 60,
          label: "岗位新增",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "job:add",
          pid: 37,
          subCount: 0,
          title: "岗位新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:58:45",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 61,
          label: "岗位编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "job:edit",
          pid: 37,
          subCount: 0,
          title: "岗位编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 12:59:04",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 62,
          label: "岗位删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "job:del",
          pid: 37,
          subCount: 0,
          title: "岗位删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:00:17",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 64,
          label: "字典新增",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "dict:add",
          pid: 39,
          subCount: 0,
          title: "字典新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:00:42",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 65,
          label: "字典编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "dict:edit",
          pid: 39,
          subCount: 0,
          title: "字典编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:00:59",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 66,
          label: "字典删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "dict:del",
          pid: 39,
          subCount: 0,
          title: "字典删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:07:28",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 73,
          label: "任务新增",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "timing:add",
          pid: 28,
          subCount: 0,
          title: "任务新增",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:07:41",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 74,
          label: "任务编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "timing:edit",
          pid: 28,
          subCount: 0,
          title: "任务编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:07:54",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 75,
          label: "任务删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "timing:del",
          pid: 28,
          subCount: 0,
          title: "任务删除",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:09:09",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 77,
          label: "上传文件",
          leaf: true,
          menuSort: 2,
          path: "",
          permission: "storage:add",
          pid: 18,
          subCount: 0,
          title: "上传文件",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:09:22",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 78,
          label: "文件编辑",
          leaf: true,
          menuSort: 3,
          path: "",
          permission: "storage:edit",
          pid: 18,
          subCount: 0,
          title: "文件编辑",
          type: 2
        },
        {
          cache: false,
          component: "",
          createTime: "2019-10-29 13:09:34",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "",
          id: 79,
          label: "文件删除",
          leaf: true,
          menuSort: 4,
          path: "",
          permission: "storage:del",
          pid: 18,
          subCount: 0,
          title: "文件删除",
          type: 2
        },
        {
          cache: false,
          component: "monitor/server/index",
          componentName: "ServerMonitor",
          createTime: "2019-11-07 13:06:39",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "codeConsole",
          id: 80,
          label: "服务监控",
          leaf: true,
          menuSort: 14,
          path: "server",
          permission: "monitor:list",
          pid: 6,
          subCount: 0,
          title: "服务监控",
          type: 1,
          updateTime: "2020-05-04 18:20:50"
        },
        {
          cache: true,
          component: "generator/config",
          componentName: "GeneratorConfig",
          createTime: "2019-11-17 20:08:56",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "dev",
          id: 82,
          label: "生成配置",
          leaf: true,
          menuSort: 33,
          path: "generator/config/:tableName",
          permission: "",
          pid: 36,
          subCount: 0,
          title: "生成配置",
          type: 1
        },
        {
          cache: true,
          component: "components/Echarts",
          componentName: "Echarts",
          createTime: "2019-11-21 09:04:32",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "chart",
          id: 83,
          label: "图表库",
          leaf: true,
          menuSort: 50,
          path: "echarts",
          permission: "",
          pid: 10,
          subCount: 0,
          title: "图表库",
          type: 1
        },
        {
          cache: false,
          component: "",
          componentName: "Mnt",
          createTime: "2019-11-09 10:31:08",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "mnt",
          id: 90,
          label: "运维管理",
          leaf: false,
          menuSort: 20,
          path: "mnt",
          subCount: 5,
          title: "运维管理",
          type: 1
        },
        {
          cache: false,
          component: "mnt/server/index",
          componentName: "ServerDeploy",
          createTime: "2019-11-10 10:29:25",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "server",
          id: 92,
          label: "服务器",
          leaf: false,
          menuSort: 22,
          path: "mnt/serverDeploy",
          permission: "serverDeploy:list",
          pid: 90,
          subCount: 3,
          title: "服务器",
          type: 1
        },
        {
          cache: false,
          component: "mnt/app/index",
          componentName: "App",
          createTime: "2019-11-10 11:05:16",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "app",
          id: 93,
          label: "应用管理",
          leaf: false,
          menuSort: 23,
          path: "mnt/app",
          permission: "app:list",
          pid: 90,
          subCount: 3,
          title: "应用管理",
          type: 1
        },
        {
          cache: false,
          component: "mnt/deploy/index",
          componentName: "Deploy",
          createTime: "2019-11-10 15:56:55",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "deploy",
          id: 94,
          label: "部署管理",
          leaf: false,
          menuSort: 24,
          path: "mnt/deploy",
          permission: "deploy:list",
          pid: 90,
          subCount: 3,
          title: "部署管理",
          type: 1
        }
      ],
      name: "超级管理员",
      updateTime: "2020-08-06 16:10:24"
    },
    {
      createTime: "2018-11-23 13:09:06",
      dataScope: "自定义",
      depts: [
        {
          createBy: "admin",
          createTime: "2019-03-25 09:52:18",
          deptSort: 6,
          enabled: true,
          hasChildren: false,
          id: 6,
          label: "测试部",
          leaf: true,
          name: "测试部",
          pid: 8,
          subCount: 0,
          updateTime: "2020-06-08 11:59:21"
        }
      ],
      description: "-",
      id: 2,
      level: 2,
      menus: [
        {
          cache: false,
          component: "components/MarkDown",
          componentName: "Markdown",
          createTime: "2019-03-08 13:46:44",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "markdown",
          id: 33,
          label: "Markdown",
          leaf: true,
          menuSort: 53,
          path: "markdown",
          pid: 10,
          subCount: 0,
          title: "Markdown",
          type: 1
        },
        {
          cache: false,
          component: "components/YamlEdit",
          componentName: "YamlEdit",
          createTime: "2019-03-08 15:49:40",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "dev",
          id: 34,
          label: "Yaml编辑器",
          leaf: true,
          menuSort: 54,
          path: "yaml",
          pid: 10,
          subCount: 0,
          title: "Yaml编辑器",
          type: 1
        },
        {
          cache: false,
          component: "",
          createTime: "2019-03-29 10:57:35",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "sys-tools",
          id: 36,
          label: "系统工具",
          leaf: false,
          menuSort: 30,
          path: "sys-tools",
          subCount: 7,
          title: "系统工具",
          type: 0
        },
        {
          cache: true,
          component: "generator/preview",
          componentName: "Preview",
          createTime: "2019-11-26 14:54:36",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "java",
          id: 116,
          label: "生成预览",
          leaf: true,
          menuSort: 999,
          path: "generator/preview/:tableName",
          pid: 36,
          subCount: 0,
          title: "生成预览",
          type: 1
        },
        {
          cache: false,
          createTime: "2018-12-18 15:11:29",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "system",
          id: 1,
          label: "系统管理",
          leaf: false,
          menuSort: 1,
          path: "system",
          subCount: 8,
          title: "系统管理",
          type: 0
        },
        {
          cache: false,
          component: "system/user/index",
          componentName: "User",
          createTime: "2018-12-18 15:14:44",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "peoples",
          id: 2,
          label: "用户管理",
          leaf: false,
          menuSort: 2,
          path: "user",
          permission: "user:list",
          pid: 1,
          subCount: 3,
          title: "用户管理",
          type: 1,
          updateTime: "2020-09-06 17:29:33"
        },
        {
          cache: false,
          createTime: "2018-12-18 15:17:48",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "monitor",
          id: 6,
          label: "系统监控",
          leaf: false,
          menuSort: 10,
          path: "monitor",
          subCount: 5,
          title: "系统监控",
          type: 0
        },
        {
          cache: true,
          component: "monitor/log/index",
          componentName: "Log",
          createTime: "2018-12-18 15:18:26",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "log",
          id: 7,
          label: "操作日志",
          leaf: true,
          menuSort: 11,
          path: "logs",
          pid: 6,
          subCount: 0,
          title: "操作日志",
          type: 1,
          updateTime: "2020-06-06 13:11:57"
        },
        {
          cache: false,
          component: "monitor/sql/index",
          componentName: "Sql",
          createTime: "2018-12-18 15:19:34",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "sqlMonitor",
          id: 9,
          label: "SQL监控",
          leaf: true,
          menuSort: 18,
          path: "druid",
          pid: 6,
          subCount: 0,
          title: "SQL监控",
          type: 1
        },
        {
          cache: false,
          createTime: "2018-12-19 13:38:16",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "zujian",
          id: 10,
          label: "组件管理",
          leaf: false,
          menuSort: 50,
          path: "components",
          subCount: 5,
          title: "组件管理",
          type: 0
        },
        {
          cache: false,
          component: "components/icons/index",
          componentName: "Icons",
          createTime: "2018-12-19 13:38:49",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "icon",
          id: 11,
          label: "图标库",
          leaf: true,
          menuSort: 51,
          path: "icon",
          pid: 10,
          subCount: 0,
          title: "图标库",
          type: 1
        },
        {
          cache: false,
          component: "tools/email/index",
          componentName: "Email",
          createTime: "2018-12-27 10:13:09",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "email",
          id: 14,
          label: "邮件工具",
          leaf: true,
          menuSort: 35,
          path: "email",
          pid: 36,
          subCount: 0,
          title: "邮件工具",
          type: 1
        },
        {
          cache: false,
          component: "components/Editor",
          componentName: "Editor",
          createTime: "2018-12-27 11:58:25",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "fwb",
          id: 15,
          label: "富文本",
          leaf: true,
          menuSort: 52,
          path: "tinymce",
          pid: 10,
          subCount: 0,
          title: "富文本",
          type: 1
        },
        {
          cache: false,
          component: "monitor/server/index",
          componentName: "ServerMonitor",
          createTime: "2019-11-07 13:06:39",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "codeConsole",
          id: 80,
          label: "服务监控",
          leaf: true,
          menuSort: 14,
          path: "server",
          permission: "monitor:list",
          pid: 6,
          subCount: 0,
          title: "服务监控",
          type: 1,
          updateTime: "2020-05-04 18:20:50"
        },
        {
          cache: true,
          component: "generator/config",
          componentName: "GeneratorConfig",
          createTime: "2019-11-17 20:08:56",
          hasChildren: false,
          hidden: true,
          iFrame: false,
          icon: "dev",
          id: 82,
          label: "生成配置",
          leaf: true,
          menuSort: 33,
          path: "generator/config/:tableName",
          permission: "",
          pid: 36,
          subCount: 0,
          title: "生成配置",
          type: 1
        },
        {
          cache: false,
          component: "tools/aliPay/index",
          componentName: "AliPay",
          createTime: "2018-12-31 14:52:38",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "alipay",
          id: 19,
          label: "支付宝工具",
          leaf: true,
          menuSort: 37,
          path: "aliPay",
          pid: 36,
          subCount: 0,
          title: "支付宝工具",
          type: 1
        },
        {
          cache: true,
          component: "components/Echarts",
          componentName: "Echarts",
          createTime: "2019-11-21 09:04:32",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "chart",
          id: 83,
          label: "图表库",
          leaf: true,
          menuSort: 50,
          path: "echarts",
          permission: "",
          pid: 10,
          subCount: 0,
          title: "图表库",
          type: 1
        },
        {
          cache: false,
          component: "",
          createTime: "2019-01-04 16:22:03",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 21,
          label: "多级菜单",
          leaf: false,
          menuSort: 900,
          path: "nested",
          subCount: 2,
          title: "多级菜单",
          type: 0,
          updateTime: "2020-06-21 17:27:35"
        },
        {
          cache: false,
          component: "",
          createTime: "2019-01-04 16:23:29",
          hasChildren: true,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 22,
          label: "二级菜单1",
          leaf: false,
          menuSort: 900,
          path: "menu1",
          pid: 21,
          subCount: 2,
          title: "二级菜单1",
          type: 0,
          updateTime: "2020-12-19 17:28:06"
        },
        {
          cache: false,
          component: "nested/menu2/index",
          createTime: "2019-01-04 16:23:57",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 23,
          label: "二级菜单2",
          leaf: true,
          menuSort: 999,
          path: "menu2",
          pid: 21,
          subCount: 0,
          title: "二级菜单2",
          type: 1
        },
        {
          cache: true,
          component: "nested/menu1/menu1-1",
          componentName: "Test",
          createTime: "2019-01-04 16:24:48",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 24,
          label: "三级菜单1",
          leaf: true,
          menuSort: 998,
          path: "menu1-1",
          pid: 22,
          subCount: 0,
          title: "三级菜单1",
          type: 1,
          updateTime: "2020-12-19 17:37:23"
        },
        {
          cache: false,
          component: "nested/menu1/menu1-2",
          createTime: "2019-01-07 17:27:32",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "menu",
          id: 27,
          label: "三级菜单2",
          leaf: true,
          menuSort: 999,
          path: "menu1-2",
          pid: 22,
          subCount: 0,
          title: "三级菜单2",
          type: 1
        },
        {
          cache: true,
          component: "generator/index",
          componentName: "GeneratorIndex",
          createTime: "2019-01-11 15:45:55",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "dev",
          id: 30,
          label: "代码生成",
          leaf: true,
          menuSort: 32,
          path: "generator",
          pid: 36,
          subCount: 0,
          title: "代码生成",
          type: 1
        },
        {
          cache: false,
          component: "monitor/log/errorLog",
          componentName: "ErrorLog",
          createTime: "2019-01-13 13:49:03",
          hasChildren: false,
          hidden: false,
          iFrame: false,
          icon: "error",
          id: 32,
          label: "异常日志",
          leaf: true,
          menuSort: 12,
          path: "errorLog",
          pid: 6,
          subCount: 0,
          title: "异常日志",
          type: 1
        }
      ],
      name: "普通用户",
      updateTime: "2020-09-05 10:45:12"
    }
  ],
  totalCount: 2
};
const rolesLevel = { level: 1 };
const menusLazy = [
  {
    cache: false,
    createTime: "2018-12-18 15:11:29",
    hasChildren: true,
    hidden: false,
    iFrame: false,
    icon: "system",
    id: 1,
    label: "系统管理",
    leaf: false,
    menuSort: 1,
    path: "system",
    subCount: 8,
    title: "系统管理",
    type: 0
  },
  {
    cache: false,
    createTime: "2018-12-18 15:17:48",
    hasChildren: true,
    hidden: false,
    iFrame: false,
    icon: "monitor",
    id: 6,
    label: "系统监控",
    leaf: false,
    menuSort: 10,
    path: "monitor",
    subCount: 5,
    title: "系统监控",
    type: 0
  },
  {
    cache: false,
    createTime: "2018-12-19 13:38:16",
    hasChildren: true,
    hidden: false,
    iFrame: false,
    icon: "zujian",
    id: 10,
    label: "组件管理",
    leaf: false,
    menuSort: 50,
    path: "components",
    subCount: 5,
    title: "组件管理",
    type: 0
  },
  {
    cache: false,
    component: "",
    createTime: "2019-01-04 16:22:03",
    hasChildren: true,
    hidden: false,
    iFrame: false,
    icon: "menu",
    id: 21,
    label: "多级菜单",
    leaf: false,
    menuSort: 900,
    path: "nested",
    subCount: 2,
    title: "多级菜单",
    type: 0,
    updateTime: "2020-06-21 17:27:35"
  },
  {
    cache: false,
    component: "",
    createTime: "2019-03-29 10:57:35",
    hasChildren: true,
    hidden: false,
    iFrame: false,
    icon: "sys-tools",
    id: 36,
    label: "系统工具",
    leaf: false,
    menuSort: 30,
    path: "sys-tools",
    subCount: 7,
    title: "系统工具",
    type: 0
  },
  {
    cache: false,
    component: "",
    componentName: "Mnt",
    createTime: "2019-11-09 10:31:08",
    hasChildren: true,
    hidden: false,
    iFrame: false,
    icon: "mnt",
    id: 90,
    label: "运维管理",
    leaf: false,
    menuSort: 20,
    path: "mnt",
    subCount: 5,
    title: "运维管理",
    type: 1
  }
];
// 菜单管理
const apiMenus = {
  content: [
    {
      cache: false,
      createTime: "2018-12-18 15:11:29",
      hasChildren: true,
      hidden: false,
      iFrame: false,
      icon: "system",
      id: 1,
      label: "系统管理",
      leaf: false,
      menuSort: 1,
      path: "system",
      subCount: 7,
      title: "系统管理",
      type: 0
    },
    {
      cache: false,
      createTime: "2018-12-18 15:17:48",
      hasChildren: true,
      hidden: false,
      iFrame: false,
      icon: "monitor",
      id: 6,
      label: "系统监控",
      leaf: false,
      menuSort: 10,
      path: "monitor",
      subCount: 5,
      title: "系统监控",
      type: 0
    },
    {
      cache: false,
      component: "",
      componentName: "Mnt",
      createTime: "2019-11-09 10:31:08",
      hasChildren: true,
      hidden: false,
      iFrame: false,
      icon: "mnt",
      id: 90,
      label: "运维管理",
      leaf: false,
      menuSort: 20,
      path: "mnt",
      subCount: 5,
      title: "运维管理",
      type: 1
    },
    {
      cache: false,
      component: "",
      createTime: "2019-03-29 10:57:35",
      hasChildren: true,
      hidden: false,
      iFrame: false,
      icon: "sys-tools",
      id: 36,
      label: "系统工具",
      leaf: false,
      menuSort: 30,
      path: "sys-tools",
      subCount: 7,
      title: "系统工具",
      type: 0
    },
    {
      cache: false,
      createTime: "2018-12-19 13:38:16",
      hasChildren: true,
      hidden: false,
      iFrame: false,
      icon: "zujian",
      id: 10,
      label: "组件管理",
      leaf: false,
      menuSort: 50,
      path: "components",
      subCount: 5,
      title: "组件管理",
      type: 0
    },
    {
      cache: false,
      component: "",
      createTime: "2019-01-04 16:22:03",
      hasChildren: true,
      hidden: false,
      iFrame: false,
      icon: "menu",
      id: 21,
      label: "多级菜单",
      leaf: false,
      menuSort: 900,
      path: "nested",
      subCount: 2,
      title: "多级菜单",
      type: 0,
      updateTime: "2020-06-21 17:27:35"
    }
  ],
  totalCount: 6
};

// 部门管理
//岗位管理
const apiJob = {
  content: [
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发1",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发2",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发3",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发4",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发5",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发6",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发7",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发8",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发9",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-31 13:39:30",
      enabled: true,
      id: 11,
      jobSort: 2,
      name: "全栈开发10",
      updateTime: "2020-05-05 11:33:43"
    },
    {
      createTime: "2019-03-29 14:52:28",
      enabled: true,
      id: 8,
      jobSort: 3,
      name: "人事专员"
    },
    {
      createTime: "2019-03-29 14:55:51",
      enabled: true,
      id: 10,
      jobSort: 4,
      name: "产品经理"
    },
    {
      createTime: "2019-03-31 13:39:43",
      enabled: true,
      id: 12,
      jobSort: 5,
      name: "软件测试",
      updateTime: "2020-05-10 19:56:26"
    }
  ],
  totalCount: 4
};

// 字典管理
const apiDict = {
  content: [
    {
      createTime: "2019-10-27 20:31:36",
      description: "岗位状态",
      dictDetails: [
        { dict: { id: 5 }, dictSort: 1, id: 5, label: "启用", value: "true" },
        {
          createTime: "2019-10-27 20:31:36",
          dict: { id: 5 },
          dictSort: 2,
          id: 6,
          label: "停用",
          value: "false"
        }
      ],
      id: 5,
      name: "job_status"
    },
    {
      createTime: "2019-10-27 20:31:36",
      description: "部门状态",
      dictDetails: [
        { dict: { id: 4 }, dictSort: 1, id: 3, label: "启用", value: "true" },
        {
          createTime: "2019-10-27 20:31:36",
          dict: { id: 4 },
          dictSort: 2,
          id: 4,
          label: "停用",
          value: "false"
        }
      ],
      id: 4,
      name: "dept_status"
    },
    {
      createTime: "2019-10-27 20:31:36",
      description: "用户状态",
      dictDetails: [
        {
          createTime: "2019-10-27 20:31:36",
          dict: { id: 1 },
          dictSort: 1,
          id: 1,
          label: "激活",
          value: "true"
        },
        { dict: { id: 1 }, dictSort: 2, id: 2, label: "禁用", value: "false" }
      ],
      id: 1,
      name: "user_status"
    }
  ],
  totalCount: 3
};
// 任务调度
const apiJobs = {
  content: [
    {
      beanName: "testTask",
      createBy: "admin",
      createTime: "2020-05-05 20:35:41",
      cronExpression: "0/5 * * * * ?",
      description: "mmt",
      email: "1",
      id: 6,
      isPause: true,
      jobName: "CQ",
      methodName: "run2",
      params: "111",
      pauseAfterFailure: true,
      personInCharge: "33",
      subTask: "2,3",
      updateBy: "admin",
      updateTime: "2021-04-12 15:17:52"
    },
    {
      beanName: "test",
      createBy: "admin",
      createTime: "2020-05-05 20:32:41",
      cronExpression: "0/5 * * * * ?",
      description: "测试",
      email: "",
      id: 5,
      isPause: true,
      jobName: "任务告警测试",
      methodName: "run",
      params: "1",
      pauseAfterFailure: false,
      personInCharge: "test2",
      updateBy: "admin",
      updateTime: "2021-04-09 10:11:59"
    },
    {
      beanName: "testTask",
      createTime: "2019-09-26 16:44:39",
      cronExpression: "0/5 * * * * ?",
      description: "不带参测试",
      email: "",
      id: 3,
      isPause: true,
      jobName: "测试",
      methodName: "run",
      params: "",
      pauseAfterFailure: false,
      personInCharge: "Zheng Jie",
      subTask: "5,6",
      updateBy: "admin",
      updateTime: "2021-03-30 15:27:30"
    },
    {
      beanName: "testTask",
      createTime: "2019-08-22 14:08:29",
      cronExpression: "0/5 1 * * * ?",
      description: "带参测试，多参使用jsonSDSDFDSFDFDSFDF",
      id: 2,
      isPause: true,
      jobName: "测试3",
      methodName: "run1",
      params: "testasd969",
      pauseAfterFailure: true,
      personInCharge: "测试3",
      updateBy: "admin",
      updateTime: "2021-03-30 11:45:22"
    }
  ],
  totalCount: 4
};
module.exports = {
  dictDetail,
  users,
  dept,
  apiRoles,
  rolesLevel,
  menusLazy,
  apiMenus,
  apiJob,
  apiDict,
  apiJobs
};
